// Contact link used in package details and contact category
const CONTACT_URL = "https://t.me/"; // TODO: replace with real contact username/URL
const CONTACT_LABEL = "Biz bilan bog‘laning";

const CATEGORIES = [
  { id: "umra",     title: "Umra paketlar",       short: "Umra"        },
  { id: "visa",     title: "Vizalar",             short: "Vizalar"     },
  { id: "hotels",   title: "Mexmonxonalar",       short: "Mexmonxona"  },
  { id: "transfer", title: "Transferlar",         short: "Transfer"    },
  { id: "contact",  title: "Biz bilan bog‘laning", short: "Aloqa"      },
];

const UMRA_PACKAGES = [
  {
    id: "vip",
    title: "VIP Paket",
    emoji: "🏆",
    lines: [
      "🕋 Makkah va Madinadagi Haramga piyoda chiqishingiz mumkin bo‘lgan 5 yulduzli mehmonxonalar",
      "✈️ Aviabiletlar: Business klass yoki siz istagan holatda",
      "🚄 Qulay transport: Train / GMC / Kia Carnival",
      "🤝 To‘liq VIP xizmat va doimiy kuzatuv",
      "📅 Siz xohlagan kun tartibida",
      "🥘 BB / HB ko‘rinishida",
      "",
      "👨‍👩‍👧‍👦 5–6 kishilik kichik guruhlar bilan tashkil etiladi",
      "",
      "✨ Maksimal qulaylik, minimal tashvish — barchasi siz uchun",
    ],
  },
  {
    id: "comfort",
    title: "Comfort Paket",
    emoji: "⭐",
    lines: [
      "🕋 Masjid ul-Haramdan uzoq bo‘lmagan (~500 m) qulay mehmonxonalar",
      "✈️ Aviabiletlar: standart tarif",
      "🚐 Transport: Avtobus / Train / Kia Carnival",
      "🤝 Tartibli tashkilot va doimiy kuzatuv",
      "📅 11 / 14 kunlik paketlar",
      "🥘 BB / HB ko‘rinishida",
      "",
      "👥 20–30 kishilik guruhlar bilan amalga oshiriladi",
      "",
      "✨ Qulaylik va sifat uyg‘unligi — eng maqbul tanlov",
    ],
  },
  {
    id: "standard",
    title: "Standard Paket",
    emoji: "⭐",
    lines: [
      "🕋 Makkah va Madinadagi Haramdan ~1–2 km masofadagi mehmonxonalar",
      "🗓 14 kunlik dastur: (3 kun Makkah / 11 kun Madina)",
      "✈️ Aviabiletlar: standart tarif",
      "",
      "🍽 Ovqatlanish:",
      "— Madinada 3 mahal",
      "— Makkada 2 mahal",
      "",
      "🚐 Transport: avtobus xizmati",
      "👳‍♂️ Guruh bilan ellikboshi (rahbar) xizmati",
      "",
      "👥 Guruh bilan tartibli va qulay ziyorat",
      "",
      "✨ Eng muvozanatli variant — narx va sifat uyg‘unligi",
    ],
  },
  {
    id: "ekonom",
    title: "Ekonom Paket",
    emoji: "💰",
    lines: [
      "🕋 Haramdan 3–7 km uzoqlikdagi qulay mehmonxonalar",
      "🛏 4–5 kishilik joylashuv",
      "",
      "🗓 14 kunlik dastur:",
      "— 12 kun Makkah",
      "— 2 kun Madina",
      "",
      "🍽 Ovqatlanish:",
      "— Makkada 3 mahal",
      "— Madinada 2 mahal",
      "",
      "✈️ Aviabiletlar: oddiy tarif",
      "🚐 Transport: avtobus xizmati",
      "👳‍♂️ Ellikboshi (rahbar) xizmati",
      "",
      "👥 40–50 kishilik guruhlar bilan tashkil etiladi",
      "",
      "✨ Eng maqbul narx — baraka va imkoniyat bir joyda",
    ],
  },
];
